language: node_js
dist: trusty
node_js:
  - "9"
install:
  - npm install
script:
  - chmod +x ./deploy.sh
  - npm run build
  - \cp -f CNAME public/CNAME
  - \cp -f favicon.ico public/favicon.ico
  - ./deploy.sh > /dev/null
cache:
  directories:
    - node_modules
