language: node_js
dist: trusty
node_js:
  - "9"
install:
  - npm install
script:
  - npm run build
  - \cp -f CNAME public/CNAME
  - \cp -f favicon.ico public/favicon.ico
 after_script:
  - git init
  - git config --global push.default matching
  - git config --global user.email "${GitHubEMail}"
  - git config --global user.name "${GitHubUser}"
  - git add --all .
  - git commit -m "Auto Builder of Planet"
  - git push --quiet --force https://${GitHubKEY}@github.com/${GitHubRepo}.git master
cache:
  directories:
    - node_modules
