language: node_js
dist: trusty
node_js:
  - "9"
install:
  - npm install
script:
  - npm run build
after_script:
  - git init
  - git config --global user.email "${GitHubEMail}"
  - git config --global user.name "${GitHubUser}"
  - git add --all .
  - git commit -m "Auto Builder of Planet"
  - git push --quiet --force "https://aiokr:${GitHubKEY}@{GH_REF}" master:master
cache:
  directories:
    - node_modules
