language: node_js
dist: trusty
node_js:
  - "9"
install:
  - npm install
script:
  - npm run build
after_script:
  - git init
  - git config --global user.name "${GitHubUser}"
  - git config --global user.email "${GitHubEMail}"
  - git clone https://${GitHubKEY}@github.com/${GitHubUser}/planet-page.git
  - git add --all .
  - git commit -m "Auto Builder of Planet"
  - git push --force "https://${GitHubKEY}@github.com/${GitHubUser}/planet-page.git" master:master
cache:
  directories:
    - node_modules
