language: node_js
dist: trusty
node_js:
  - "7"
install:
  - npm install
script:
  - \cp -i -f generate.js node_modules/planet.js/lib/generate.js
  - chmod +x ./deploy.sh
  - npm run build
  - ./deploy.sh > /dev/null
cache:
  directories:
    - node_modules
