language: node_js
dist: trusty
node_js:
  - "7"
install:
  - npm install
script:
#  - chmod +x ../patch.sh
  - chmod +x ../deploy.sh
#  - ../patch.sh > /dev/null
  - npm run build
  - ../deploy.sh > /dev/null
branches:
  only:
    - raw
cache:
  directories:
    - node_modules
