# planet.js configuration

planet:
  name: "neoFelhz's Planet" # Site title
  tagline: "neoFelhz 的伙伴星球" # Site tagline
  description: "neoFelhz 的伙伴星球" # Site description
  link: https://planet.nfz.moe # Site link, do NOT include tailing slash '/'
  locale: zh-CN # Site locale
  owner_name: neoFelhz # Your name
  owner_email: neoFelhz@gmail.com # Your email
  theme: pure # theme under templates directory
  output: public # output directory, make sure your web server can read in this place
  timeout: 40 # request timeout in seconds
  items: 150 # how many posts should be displayed?
  items_feed: 200 # maximum posts in feed
  display_length: 500 # posts longer than this characters, a summary will be displayed (if available)
  time_format: MMMM Do YYYY h:mm:ss A # See http://momentjs.com/docs/#/displaying/ for details
  ttl: 120 # TimeToLive minutes to cache site feed

secure:
  proxy: # Leave blank if you don't use an http proxy
  allowedTags: # set to true to allow any tags, or [] to disallow any.
  - h1
  - h2
  - h3
  - h4
  - h5
  - h6
  - blockquote
  - p
  - a
  - ul
  - ol
  - nl
  - li
  - b
  - i
  - s
  - g
  - strong
  - em
  - strike
  - del
  - pre
  - code
  - kbd
  - hr
  - br
  - div
  - table
  - thead
  - tbody
  - tr
  - th
  - td
  - caption
  - img
  - sup
  - sub
  - span
  - font
  - style
  - svg
  - defs
  - path
  - use
  allowedAttributes:
    a:
    - href
    - name
    - target
    img:
    - src
  selfClosing:
  - img
  - br
  - hr
  allowedSchemes:
  - http
  - https
  - ftp
  - mailto
  allowProtocolRelative: true

people:
- name: SkyEdge
  link: https://liyin.date/rss2.xml
  avatar: https://img1.nfz.yecdn.com/avatar/liyin.date.png
- name: Viosey
  link: https://blog.viosey.com/atom.xml
  avatar: https://img1.nfz.yecdn.com/avatar/viosey.com.png
- name: 蠢黑通行
  link: https://blackyau.cc/feed
  avatar: https://img1.nfz.yecdn.com/links/blackyau.cc.jpg
- name: Zohar
  link: https://www.iwch.me/feed
  avatar: https://img1.nfz.yecdn.com/links/www.iwch.me.jpg
- name: Trumeet
  link: https://blog.trumeet.top/atom.xml
  avatar: https://img1.nfz.yecdn.com/links/trumeet.top.png
- name: MaxFox
  link: https://maxfox.me/atom.xml
  avatar: https://img1.nfz.yecdn.com/links/maxfox.me.png
- name: LWL12
  link: https://blog.lwl12.com/feed
  avatar: https://img1.nfz.yecdn.com/links/blog.lwl12.com.jpg
- name: Troy
  link: https://itroy.cc/feed
  avatar: https://img1.nfz.yecdn.com/links/itroy.cc.png
- name: KeJun
  link: https://blog.kejun.space/feed.xml
  avatar: https://img1.nfz.yecdn.com/links/kejun.space.png
- name: mokeyjay
  link: https://www.mokeyjay.com/feed
  avatar: https://img1.nfz.yecdn.com/links/www.mokeyjay.com.jpg
- name: Halyul
  link: https://blog.halyul.cc/atom.xml
  avatar: https://img1.nfz.yecdn.com/links/halyul.com.png
- name: Axton
  link: https://flyhigher.top/feed
  avatar: https://img1.nfz.yecdn.com/links/flyhigher.top.png
- name: PoiScript
  link: https://blog.poi.cat/atom.xml
  avatar: https://img1.nfz.yecdn.com/links/blog.poi.cat.png
- name: Netrvin
  link: https://131.re/feed
  avatar: https://img1.nfz.yecdn.com/links/131.re.jpg
- name: Ice-Hazymoon
  link: https://imiku.me/feed
  avatar: https://img1.nfz.yecdn.com/links/imiku.me.png
- name: 梦魇小站
  link: https://blog.ihoey.com/atom.xml
  avatar: https://img1.nfz.yecdn.com/links/blog.ihoey.com.png
- name: 只有一秒的记忆
  link: https://blog.asec01.net/feed.xml
  avatar: https://img1.nfz.yecdn.com/links/blog.asec01.net.png

