# planet.js configuration

planet:
  name: "neoFelhz's Planet" # Site title
  tagline: "neoFelhz 的伙伴星球" # Site tagline
  description: "neoFelhz 的伙伴星球" # Site description
  link: https://planet.nfz.moe # Site link, do NOT include tailing slash '/'
  locale: zh-CN # Site locale
  owner_name: neoFelhz # Your name
  owner_email: neoFelhz@gmail.com # Your email
  theme: mdui # theme under templates directory
  output: public # output directory, make sure your web server can read in this place
  timeout: 40 # request timeout in seconds
  items: 150 # how many posts should be displayed?
  items_feed: 300 # maximum posts in feed
  display_length: 700 # posts longer than this characters, a summary will be displayed (if available)
  time_format: MMMM Do YYYY h:mm:ss A # See http://momentjs.com/docs/#/displaying/ for details
  ttl: 120 # TimeToLive minutes to cache site feed
  lazyload: true # Use Lazyload for image
  		  
secure:
  proxy: # Leave blank if you don't use an http proxy
  allowedTags: # set to true to allow any tags, or [] to disallow any.
  - h1
  - h2
  - h3
  - h4
  - h5
  - h6
  - blockquote
  - p
  - a
  - ul
  - ol
  - nl
  - li
  - b
  - i
  - s
  - g
  - strong
  - em
  - strike
  - del
  - pre
  - code
  - kbd
  - hr
  - br
  - div
  - table
  - thead
  - tbody
  - tr
  - th
  - td
  - caption
  - img
  - sup
  - sub
  - span
  - font
  - style
  - svg
  - defs
  - path
  - use
  - [script]
  allowedAttributes:
    a:
    - href
    - name
    - target
    img:
    - src
  selfClosing:
  - img
  - br
  - hr
  allowedSchemes:
  - http
  - https
  - ftp
  - mailto
  allowProtocolRelative: true

people:
- name: neoFelhz
  link: https://blog.nfz.moe/atom.xml
  avatar: https://i.nfz.yecdn.com/avatar/avatar.png
