# planet.js configuration

planet:
  name: "aiokr's Planet" # Site title
  tagline: "aiokr 的伙伴星球" # Site tagline
  description: "aiokr 的伙伴星球" # Site description
  link: https://planet.aiokr.top # Site link, do NOT include tailing slash '/'
  locale: zh-CN # Site locale
  owner_name: aiokr # Your name
  owner_email: hiaiokr@gmail.com # Your email
  theme: pure # theme under templates directory
  output: public # output directory, make sure your web server can read in this place
  timeout: 15 # request timeout in seconds
  items: 150 # how many posts should be displayed?
  items_feed: 300 # maximum posts in feed
  display_length: 200 # posts longer than this characters, a summary will be displayed (if available)
  time_format: YYYY MMMM Do h:mm:ss A # See http://momentjs.com/docs/#/displaying/ for details
  ttl: 120 # TimeToLive minutes to cache site feed
  lazyload: true # Use Lazyload for image
  		  
secure:
  proxy: # Leave blank if you don't use an http proxy
  allowedTags: # set to true to allow any tags, or [] to disallow any.
  - h1
  - h2
  - h3
  - h4
  - h5
  - h6
  - blockquote
  - p
  - a
  - ul
  - ol
  - nl
  - li
  - b
  - i
  - s
  - g
  - strong
  - em
  - strike
  - del
  - pre
  - code
  - kbd
  - hr
  - br
  - div
  - table
  - thead
  - tbody
  - tr
  - th
  - td
  - caption
  - img
  - sup
  - sub
  - span
  - font
  - style
  - svg
  - defs
  - path
  - use
  - [script]
  allowedAttributes:
    a:
    - href
    - name
    - target
    img:
    - src
  selfClosing:
  - img
  - br
  - hr
  allowedSchemes:
  - http
  - https
  - ftp
  - mailto
  allowProtocolRelative: true

people:
- name: aiokr
  link: https://i.aiokr.com/feed/
  avatar: https://secure.gravatar.com/avatar/f17e6a2f95f817acc509242cccb6c4d2?s=220&r=X&d=mm
- name: KeJun
  link: https://blog.kejun.space/feed.xml
  avatar: https://avatars0.githubusercontent.com/u/18414281?s=400&v=4
- name: Halyul
  link: https://blog.halyul.cc/atom.xml
  avatar: https://gravatar.com/userimage/113938008/0ffede3b011b3a1725a0bae6b2db2c72.png?size=200
- name: 冰凌胧月的小窝
  link: https://imiku.me/feed/
  avatar: https://cdn.moe0pic.moe0.cn/avatar.png
